/**
 * Frontend Configuration
 * This file will be dynamically generated by the server to inject configuration
 */

// Configuration will be injected here by the server
window.CONFIG = window.CONFIG || {
    API_BASE_URL: 'http://localhost:5001/api',
    BACKEND_URL: 'http://localhost:5001',
    FRONTEND_URL: 'http://localhost:8010'
};